services:
  # Backend Service (Node.js)
  - type: web
    name: meme-server
    env: node
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add SUPABASE_URL and SUPABASE_KEY manually via Render dashboard

  # Frontend Service (Static Site)
  - type: static
    name: meme-client
    rootDir: ./client
    buildCommand: npm install && npm run build
    publishDir: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        fromService:
          name: meme-server
          type: web
          property: url
