services:
  # Backend Service (Node.js)
  - type: web
    name: meme-server
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      # Note: Add your SUPABASE_URL and SUPABASE_KEY in the Render UI
      # under Environment for the 'meme-server' service.

  # Frontend Service (Static Site)
  - type: static_site
    name: meme-client
    rootDir: client
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: meme-server
          property: url
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"